source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'rails_admin'
gem 'rails_admin_nestable'
gem 'ckeditor'
gem 'devise'
gem 'cancan'
gem 'ancestry'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'gritter', '1.0.3'
gem 'compass-rails'
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'friendly_id', github: 'norman/friendly_id'
gem 'russian'
gem 'fancybox2-rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
  gem 'thin'
  gem 'capistrano'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
end

group :production do
  gem 'unicorn'
end
